### ISSUE TITLE
Publish binaries

### ISSUE THREAD

**Issue by aalmiray** [gunnarmorling/kcctl#10]
Leverage https://jreleaser.org to publish Native Image binaries to a GitHub release.
Should configure 2 types of releases:
- a rolling snapshot release, i.e,`1.0.0-early-access`
- a stable release, i.e, `1.0.0.Alpha1`

**Comment by gunnarmorling** [comment]
Woot, woot. Thanks a lot for this initiative!

**Comment by aalmiray** [comment]
PR #12 addresses publication of Native Image binaries for Linux, Windows, and OSX on Intel arch. Additional binaries may be published such as:
- a Java based binary distribution. Requires a Java 11+ installation.
- jlink distributions. Bundle a minimal Java runtime. Can target any platform for which a JDK can be downloaded (Zulu 16+ builds support Apple Silicon for example)

These additional binaries are easy to configure with JReleaser.

**Comment by gunnarmorling** [comment]
Thanks a lot; I think for now, the native binaries are the way to go; for a snappy experience, in particular when it comes to TAB completions, the fast start-up just makes the difference.
