### ISSUE TITLE
Add option to change Log Level Dynamically

### ISSUE THREAD

**Issue by sfc-gh-japatel** [gunnarmorling/kcctl#15]
https://docs.confluent.io/platform/current/connect/logging.html#using-the-kconnect-api
Instead of changing the logs by changing the log4j properties file, this connect API helps to change the log at runtime without restarting the connector. 

Example usage:
```
curl -s -X PUT -H "Content-Type:application/json" \
                        http://localhost:8083/admin/loggers/com.snowflake.kafka.connector \
-d '{"level": "INFO"}' | jq '.'
```

May be w.r.t kcctl it can be
```kcctl logger --level DEBUG --class <Specific class or connector>```

Follow up
```kcctl logger get```

Let me know what you think?

**Comment by gunnarmorling** [comment]
Hey, yes, would definitely nice to have this. Had logged #9 for this requirement before. I think the read command should be

    kcctl get loggers
    kcctl get logger com.acme.MyConnect

for the sake of consistency with existing commands and the general idea of mimicking _kubectl_.

Re the write command adding a new first-level subcommand seems a bit heavy, but then, I don't see a compelling alternative either. One alternative I was thinking of was adding `kcctl patch config ...` for updating single configuration parameters of a connector. Perhaps this could be used too: `kcctl patch logger com.acme.MyConnect -p '{"level": "TRACE"}'`. Would that make sense?

**Comment by sfc-gh-japatel** [comment]
Hey, sorry, I didnt search in issues. 

Makes sense to follow the consistency, but I am not sure if changing the log level is counted as config parameter. So may be both are orthogonal?
(Connect has an API to alter the configuration but that requires json)

But ```kcctl patch logger <loggername> --level DEBUG``` makes sense to me.

**Comment by sfc-gh-japatel** [comment]
Ahh, I see what you were referring to. So based on patch argument, we can decide which REST API to use.

**Comment by sfc-gh-japatel** [comment]
`./mvnw compile quarkus:dev -Ddebug=6006`
Running Quarkus into debug mode, I get following error, so the server is not starting on 8080
```
 No sources to compile
Listening for transport dt_socket at address: 6006
2021-07-15 23:24:28,675 INFO  [io.quarkus] (Quarkus Main Thread) kc-cli 1.0.0-SNAPSHOT on JVM (powered by Quarkus 2.0.1.Final) started in 0.966s.
2021-07-15 23:24:28,678 INFO  [io.quarkus] (Quarkus Main Thread) Profile dev activated. Live Coding activated.
2021-07-15 23:24:28,678 INFO  [io.quarkus] (Quarkus Main Thread) Installed features: [cdi, picocli, rest-client, rest-client-jackson]
Missing required subcommand
Usage: kcctl [COMMAND]
A command-line interface for Kafka Connect
Commands:
  info      Displays information about the Kafka Connect cluster
  config    Sets or retrieves the configuration of this client
  get       Displays information about connector plug-ins and connectors
  delete    Deletes the specified connector
  restart   Restarts a connector or task
  describe  Displays detailed information about the specified resource
  apply     Applies the given file for registering or updating a connector
  help      Displays help information about the specified command
2021-07-15 23:24:28,731 INFO  [io.quarkus] (Quarkus Main Thread) kc-cli stopped in 0.002s
Quarkus application exited with code 2
```
What am I missing?

**Comment by gunnarmorling** [comment]
Done. Thx, @sfc-gh-japatel!

**Comment by gunnarmorling** [comment]
Pushed some more commits to make tab completion work too and also re-order commands a bit.
